# home-manager module: programs.wimy.
#
# macOS: the activation copies Wimy.app out of the store to installDir
# (a stable, writable path — wimy's in-place restart re-executes the
# path it runs from, and the signature, not the path, carries the
# Accessibility permission), links wimyctl into ~/.local/bin, and then
# restarts a running wimy in place (state kept; the new build is checked
# first) or starts it. Login start is wimy's own start-at-login.
# Batteries included: SketchyBar (through home-manager's
# programs.sketchybar) with wimy's bar config from
# contrib/macos/sketchybar, its Nerd Font, the native menu bar hidden,
# and wimy's bar-gap set to the bar's height. sketchybar.enable = false
# leaves all of that to you. Window corners are squared to match wimy's
# borders (windowCornerRadius; home-manager writes the global default,
# no nix-darwin needed).
# Linux: installs the package; start it from river (`river -c wimy`).
self:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.wimy;
  inherit (pkgs.stdenv.hostPlatform) isDarwin;
  app = "${cfg.installDir}/Wimy.app";
  bar = cfg.sketchybar;
  barOn = isDarwin && bar.enable;

  # contrib/macos/sketchybar plus the generated settings.sh and extra.sh
  barConfig = pkgs.runCommand "wimy-sketchybar-config" { } ''
    cp -r ${../contrib/macos/sketchybar} $out
    chmod -R u+w $out
    rm -f $out/README.md
    cp ${pkgs.writeText "settings.sh" ''
      # Generated by the wimy home-manager module (programs.wimy.sketchybar).
      BAR_HEIGHT=${toString bar.height}
      FONT=${lib.escapeShellArg bar.font.family}
      WIMYCTL=${lib.escapeShellArg "${app}/Contents/MacOS/wimyctl"}
    ''} $out/settings.sh
    cp ${pkgs.writeText "extra.sh" bar.extraConfig} $out/extra.sh
  '';

  menuOn = isDarwin && cfg.menu.enable;
  kdlString = s: "\"" + lib.escape [ "\\" "\"" ] s + "\"";

  # wimy's own config: the module's lines first, so the user's settings
  # can override them
  configText =
    lib.optionalString menuOn "// the choose picker (programs.wimy.menu)\nmenu ${kdlString cfg.menu.command}\n"
    + lib.optionalString barOn "// reserved for SketchyBar (programs.wimy.sketchybar.height)\nbar-gap ${toString bar.height}\n"
    + lib.optionalString (builtins.isString cfg.settings) cfg.settings;
in
{
  options.programs.wimy = {
    enable = lib.mkEnableOption "wimy, a wmii-style tiling window manager";
    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${pkgs.stdenv.hostPlatform.system}.wimy;
      defaultText = lib.literalExpression "wimy.packages.\${system}.wimy";
      description = "The wimy package (on macOS: the signed release app).";
    };
    settings = lib.mkOption {
      type = with lib.types; nullOr (either path lines);
      default = "";
      example = ''
        terminal "open -na Ghostty"
      '';
      description = ''
        ~/.config/wimy/config.kdl, as KDL text (wimy's defaults apply to
        everything it doesn't set) or a path. With the bundled SketchyBar,
        text gets `bar-gap` matching the bar's height prepended; a path
        is used as is (set `bar-gap` in it yourself). null leaves the file
        alone, e.g. to keep an out-of-store link for live
        `wimyctl run reload` edits.
      '';
    };
    installDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/Applications";
      description = "Where Wimy.app is installed on macOS.";
    };

    menu = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          macOS: install choose (a dmenu-style picker) and make it wimy's
          `menu`: the app picker (Mod-p), the action menu (Mod-a) and the
          view prompts. wimy runs as a launchd agent without your PATH,
          so the command names it by its store path.
        '';
      };
      command = lib.mkOption {
        type = lib.types.str;
        default = "${pkgs.choose-gui}/bin/choose -n 12 -w 40 -s 16 -u -c 8aadf4 -b 363a4f -f ${lib.escapeShellArg cfg.sketchybar.font.family}";
        defaultText = lib.literalExpression ''"''${pkgs.choose-gui}/bin/choose -n 12 -w 40 -s 16 -u -c 8aadf4 -b 363a4f -f '<bar font>'"'';
        description = ''
          The menu command line (run through sh -c; wimy appends `-p
          <label>` and feeds the choices on stdin). Catppuccin Macchiato
          colors and the bar's font by default.
        '';
      };
    };

    windowCornerRadius = lib.mkOption {
      type = lib.types.nullOr (lib.types.numbers.between 1 50);
      default = 1;
      example = 10;
      description = ''
        macOS: corner radius of every app's windows, in points (the
        global `NSConvolutionOverride1` default). 1 is square, matching
        wimy's borders (0 is ignored by macOS); 10 is the pre-Tahoe look,
        26 Tahoe's. Apps pick it up when they start; log out and back in
        for all of them. Chromium-based browsers ignore it. null leaves
        the setting alone; to undo a value set before, run
        `defaults delete -g NSConvolutionOverride1`.
      '';
    };

    sketchybar = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Whether to set up SketchyBar on macOS with wimy's bar config
          (views, column mode, status items): home-manager's
          programs.sketchybar and its launchd agent, the bar's font, the
          native menu bar hidden, and wimy's `bar-gap`. Turn it off to
          configure SketchyBar (or another bar) yourself; the wimy plugin
          is contrib/macos/sketchybar/plugins/wimy.sh.
        '';
      };
      height = lib.mkOption {
        type = lib.types.ints.positive;
        default = 37;
        description = ''
          Bar height in points, also reserved at the top of every screen
          (wimy's `bar-gap`). 37 covers the notched MacBook menu bar.
        '';
      };
      font = {
        package = lib.mkOption {
          type = lib.types.nullOr lib.types.package;
          default = pkgs.nerd-fonts.meslo-lg;
          defaultText = lib.literalExpression "pkgs.nerd-fonts.meslo-lg";
          description = "Font package for the bar (a Nerd Font: the icons are its glyphs); null to install none.";
        };
        family = lib.mkOption {
          type = lib.types.str;
          default = "MesloLGM Nerd Font";
          description = "Font family the bar uses.";
        };
      };
      hideMenuBar = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Auto-hide the native menu bar (it shows on hover, over SketchyBar).";
      };
      extraConfig = lib.mkOption {
        type = lib.types.lines;
        default = "";
        example = ''
          sketchybar --set clock icon.color=$RED
        '';
        description = ''
          Bash run at the end of sketchybarrc, before `sketchybar
          --update`: extra items and overrides. The palette (colors.sh),
          icons (icons.sh), $PLUGIN_DIR, $FONT and $BAR_HEIGHT are
          available.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      (lib.mkIf (!isDarwin) { home.packages = [ cfg.package ]; })
      (lib.mkIf (cfg.settings != null) {
        xdg.configFile."wimy/config.kdl" =
          if builtins.isString cfg.settings then { text = configText; } else { source = cfg.settings; };
      })
      (lib.mkIf barOn {
        programs.sketchybar = {
          enable = true;
          config = {
            source = barConfig;
            recursive = true;
          };
        };
        # a running bar picks up a changed config
        xdg.configFile."sketchybar".onChange = ''
          run ${lib.getExe config.programs.sketchybar.finalPackage} --reload 2>/dev/null || true
        '';
        # launchd gives user agents no HOME; sketchybar finds its config there
        launchd.agents.sketchybar.config.EnvironmentVariables.HOME = config.home.homeDirectory;
        home.packages = lib.optional (bar.font.package != null) bar.font.package;
        targets.darwin.defaults.NSGlobalDomain._HIHideMenuBar = lib.mkIf bar.hideMenuBar true;
      })
      (lib.mkIf menuOn { home.packages = [ pkgs.choose-gui ]; })
      (lib.mkIf (isDarwin && cfg.windowCornerRadius != null) {
        targets.darwin.defaults.NSGlobalDomain.NSConvolutionOverride1 = cfg.windowCornerRadius;
      })
      (lib.mkIf isDarwin {
        home.activation.wimy = lib.hm.dag.entryAfter [ "writeBoundary" "linkGeneration" ] ''
          run mkdir -p ${lib.escapeShellArg cfg.installDir} "$HOME/.local/bin"
          # store files are read-only: make the copy writable so the next
          # update can replace it (permissions aren't part of the signature)
          run ${pkgs.rsync}/bin/rsync -a --delete --chmod=u+w \
            ${cfg.package}/Applications/Wimy.app/ ${lib.escapeShellArg app}/
          run ln -sf ${lib.escapeShellArg "${app}/Contents/MacOS/wimyctl"} "$HOME/.local/bin/wimyctl"
          if ${lib.escapeShellArg "${app}/Contents/MacOS/wimyctl"} version >/dev/null 2>&1; then
            run ${lib.escapeShellArg "${app}/Contents/MacOS/wimyctl"} restart \
              || warnEcho "wimy: restart failed; the running wimy stays (see ~/Library/Logs/wimy.log)"
          else
            run /usr/bin/open ${lib.escapeShellArg app}
          fi
        '';
      })
    ]
  );
}
